### PR TITLE
backend: Emit `Ok(...)` in the circuit constructor closure.

### PR DESCRIPTION
**Pull request by blp**
When DBSP PR #126 is committed, it will allow the closure that initializes a circuit to fail, which means that the return value from the closure will need to be wrapped in `Ok(...)`.  This commit makes that change.

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]

**Comment by mihaibudiu** [comment]
Click quickly the "merge" button on both PRs.

**Review by mihaibudiu — APPROVED** [review]

**Comment by mihaibudiu** [comment]
Many of these are present in #27 as well.

**Comment by mihaibudiu** [comment]
You have conflicts, I think you are not using the latest main.

**Comment by blp** [comment]
> Many of these are present in #27 as well.

Yeah, didn't see that until now. I'll rebase.

**Comment by blp** [comment]
> > Many of these are present in #27 as well.
> 
> Yeah, didn't see that until now. I'll rebase.

It was all duplicative, so I'm discarding it.

**Pull request merged**
